apiVersion: networking.k8s.io/v1
kind: Ingress
meta
  name: subscription-tracker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.subscriptiontracker.com
    secretName: subscription-tls
  rules:
  - host: api.subscriptiontracker.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: subscription-tracker
            port:
              number: 80
